# Generated by Django 5.0.13 on 2025-12-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ManyToManyField(to='app_estudiante.profesor'),
        ),
    ]
